name: Bench

on: [ push ]

jobs:
  unit:
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Bench
        run: go test -v -bench=. -benchmem -benchtime=60s